# Generated by Django 5.0.6 on 2024-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
