# Generated by Django 5.0.6 on 2024-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
